import argparse
import random
from datetime import date, datetime, timedelta
from typing import Dict, List, Sequence, Tuple

import psycopg


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a PostgreSQL (Supabase compatible) benchmark schema with related tables and seed data."
    )
    parser.add_argument("--host", required=True, help="Supabase pooler host, e.g. aws-0-xxx.pooler.supabase.com")
    parser.add_argument("--port", type=int, default=5432)
    parser.add_argument("--user", required=True, help="e.g. postgres.<project_ref>")
    parser.add_argument("--password", required=True)
    parser.add_argument("--database", default="postgres")
    parser.add_argument("--sslmode", default="require")
    parser.add_argument("--seed", type=int, default=20260424)
    parser.add_argument("--city-count", type=int, default=30)
    parser.add_argument("--cinema-count", type=int, default=120)
    parser.add_argument("--movie-count", type=int, default=240)
    parser.add_argument("--screening-count", type=int, default=12000)
    parser.add_argument("--customer-count", type=int, default=9000)
    parser.add_argument("--order-count", type=int, default=45000)
    parser.add_argument("--review-count", type=int, default=18000)
    parser.add_argument("--batch-size", type=int, default=1000)
    parser.add_argument(
        "--recreate",
        action="store_true",
        help="Drop existing tables (cascade) before creating them again.",
    )
    return parser.parse_args()


def connect_database(args: argparse.Namespace) -> psycopg.Connection:
    return psycopg.connect(
        host=args.host,
        port=args.port,
        user=args.user,
        password=args.password,
        dbname=args.database,
        sslmode=args.sslmode,
        autocommit=False,
    )


TABLE_DROP_ORDER = [
    "movie_reviews",
    "order_items",
    "ticket_orders",
    "screenings",
    "customers",
    "movies",
    "cinemas",
    "cities",
]

DDL_LIST: List[str] = [
    """
    CREATE TABLE IF NOT EXISTS cities (
        city_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        city_name VARCHAR(64) NOT NULL,
        region VARCHAR(32) NOT NULL,
        tier SMALLINT NOT NULL,
        population BIGINT NOT NULL,
        gdp_billion NUMERIC(10,2) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS cinemas (
        cinema_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        city_id INTEGER NOT NULL,
        cinema_name VARCHAR(128) NOT NULL,
        brand VARCHAR(64) NOT NULL,
        address VARCHAR(255) NOT NULL,
        opened_date DATE NOT NULL,
        hall_count INTEGER NOT NULL,
        seat_count INTEGER NOT NULL,
        service_score NUMERIC(3,1) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_cinemas_city FOREIGN KEY (city_id) REFERENCES cities(city_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS movies (
        movie_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title VARCHAR(128) NOT NULL,
        genre VARCHAR(32) NOT NULL,
        language VARCHAR(32) NOT NULL,
        production_country VARCHAR(32) NOT NULL,
        director VARCHAR(64) NOT NULL,
        duration_min INTEGER NOT NULL,
        release_date DATE NOT NULL,
        imdb_score NUMERIC(3,1) NOT NULL,
        box_office_million NUMERIC(10,2) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS screenings (
        screening_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cinema_id INTEGER NOT NULL,
        movie_id INTEGER NOT NULL,
        screen_type VARCHAR(16) NOT NULL,
        start_time TIMESTAMP NOT NULL,
        end_time TIMESTAMP NOT NULL,
        base_price NUMERIC(8,2) NOT NULL,
        seat_capacity INTEGER NOT NULL,
        sold_tickets INTEGER NOT NULL,
        city_weather VARCHAR(16) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_screenings_cinema FOREIGN KEY (cinema_id) REFERENCES cinemas(cinema_id),
        CONSTRAINT fk_screenings_movie FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS customers (
        customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        city_id INTEGER NOT NULL,
        customer_name VARCHAR(64) NOT NULL,
        gender CHAR(1) NOT NULL,
        birth_year INTEGER NOT NULL,
        register_date DATE NOT NULL,
        membership_level VARCHAR(16) NOT NULL,
        total_spent NUMERIC(12,2) NOT NULL DEFAULT 0,
        is_active SMALLINT NOT NULL DEFAULT 1,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_customers_city FOREIGN KEY (city_id) REFERENCES cities(city_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS ticket_orders (
        order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        customer_id BIGINT NOT NULL,
        screening_id BIGINT NOT NULL,
        order_time TIMESTAMP NOT NULL,
        ticket_count INTEGER NOT NULL,
        total_amount NUMERIC(10,2) NOT NULL,
        payment_method VARCHAR(16) NOT NULL,
        order_status VARCHAR(16) NOT NULL,
        sales_channel VARCHAR(16) NOT NULL,
        refund_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
        CONSTRAINT fk_orders_screening FOREIGN KEY (screening_id) REFERENCES screenings(screening_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS order_items (
        item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        order_id BIGINT NOT NULL,
        seat_no VARCHAR(16) NOT NULL,
        ticket_price NUMERIC(8,2) NOT NULL,
        discount_type VARCHAR(16) NOT NULL,
        snack_combo VARCHAR(32) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES ticket_orders(order_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS movie_reviews (
        review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        movie_id INTEGER NOT NULL,
        cinema_id INTEGER NOT NULL,
        customer_id BIGINT NOT NULL,
        rating INTEGER NOT NULL,
        sentiment VARCHAR(16) NOT NULL,
        review_time TIMESTAMP NOT NULL,
        content VARCHAR(255) NOT NULL,
        like_count INTEGER NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_reviews_movie FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
        CONSTRAINT fk_reviews_cinema FOREIGN KEY (cinema_id) REFERENCES cinemas(cinema_id),
        CONSTRAINT fk_reviews_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
    )
    """,
]

INDEX_LIST: List[str] = [
    "CREATE INDEX IF NOT EXISTS idx_cinemas_city_id ON cinemas(city_id)",
    "CREATE INDEX IF NOT EXISTS idx_screenings_cinema_id ON screenings(cinema_id)",
    "CREATE INDEX IF NOT EXISTS idx_screenings_movie_id ON screenings(movie_id)",
    "CREATE INDEX IF NOT EXISTS idx_screenings_start_time ON screenings(start_time)",
    "CREATE INDEX IF NOT EXISTS idx_customers_city_id ON customers(city_id)",
    "CREATE INDEX IF NOT EXISTS idx_customers_membership_level ON customers(membership_level)",
    "CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON ticket_orders(customer_id)",
    "CREATE INDEX IF NOT EXISTS idx_orders_screening_id ON ticket_orders(screening_id)",
    "CREATE INDEX IF NOT EXISTS idx_orders_order_time ON ticket_orders(order_time)",
    "CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviews_movie_id ON movie_reviews(movie_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviews_customer_id ON movie_reviews(customer_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviews_review_time ON movie_reviews(review_time)",
]


def create_tables(conn: psycopg.Connection, recreate: bool) -> None:
    with conn.cursor() as cursor:
        if recreate:
            for table_name in TABLE_DROP_ORDER:
                cursor.execute(f"DROP TABLE IF EXISTS {table_name} CASCADE")
        for ddl in DDL_LIST:
            cursor.execute(ddl)
        for index_ddl in INDEX_LIST:
            cursor.execute(index_ddl)
    conn.commit()


def random_datetime_between(rng: random.Random, start: datetime, end: datetime) -> datetime:
    delta_seconds = int((end - start).total_seconds())
    return start + timedelta(seconds=rng.randint(0, max(delta_seconds, 1)))


def chunked_rows(rows: Sequence[Tuple], batch_size: int) -> Sequence[Sequence[Tuple]]:
    for idx in range(0, len(rows), batch_size):
        yield rows[idx : idx + batch_size]


def insert_many(
    conn: psycopg.Connection,
    sql: str,
    rows: Sequence[Tuple],
    batch_size: int,
) -> None:
    if not rows:
        return
    with conn.cursor() as cursor:
        for chunk in chunked_rows(rows, batch_size):
            cursor.executemany(sql, chunk)
    conn.commit()


def seed_cities(rng: random.Random, city_count: int) -> List[Tuple]:
    regions = ["north", "east", "south", "west", "central"]
    rows: List[Tuple] = []
    for i in range(city_count):
        city_name = f"City_{i + 1:03d}"
        region = rng.choice(regions)
        tier = rng.randint(1, 5)
        population = rng.randint(1_000_000, 30_000_000)
        gdp_billion = round(rng.uniform(80, 2800), 2)
        rows.append((city_name, region, tier, population, gdp_billion))
    return rows


def seed_cinemas(rng: random.Random, cinema_count: int, city_count: int) -> List[Tuple]:
    brands = ["AlphaCinema", "SkyLine", "MovieMax", "StarHall", "VisionX"]
    rows: List[Tuple] = []
    for i in range(cinema_count):
        city_id = rng.randint(1, city_count)
        cinema_name = f"Cinema_{i + 1:04d}"
        brand = rng.choice(brands)
        address = f"{rng.randint(1, 999)} Main Street Block {rng.randint(1, 50)}"
        opened_date = date.today() - timedelta(days=rng.randint(180, 6000))
        hall_count = rng.randint(4, 18)
        seat_count = hall_count * rng.randint(60, 180)
        service_score = round(rng.uniform(6.5, 9.8), 1)
        rows.append(
            (
                city_id,
                cinema_name,
                brand,
                address,
                opened_date,
                hall_count,
                seat_count,
                service_score,
            )
        )
    return rows


def seed_movies(rng: random.Random, movie_count: int) -> List[Tuple]:
    genres = ["action", "comedy", "drama", "sci_fi", "crime", "romance", "animation", "thriller"]
    languages = ["zh", "en", "jp", "kr"]
    countries = ["CN", "US", "JP", "KR", "UK", "FR"]
    rows: List[Tuple] = []
    for i in range(movie_count):
        title = f"Movie_{i + 1:04d}"
        genre = rng.choice(genres)
        language = rng.choice(languages)
        country = rng.choice(countries)
        director = f"Director_{rng.randint(1, 800):03d}"
        duration_min = rng.randint(85, 180)
        release_date = date.today() - timedelta(days=rng.randint(0, 3650))
        imdb_score = round(rng.uniform(4.5, 9.7), 1)
        box_office_million = round(rng.uniform(1, 3200), 2)
        rows.append(
            (
                title,
                genre,
                language,
                country,
                director,
                duration_min,
                release_date,
                imdb_score,
                box_office_million,
            )
        )
    return rows


def seed_screenings(
    rng: random.Random,
    screening_count: int,
    cinema_count: int,
    movie_count: int,
) -> List[Tuple]:
    screen_types = ["2D", "3D", "IMAX", "DOLBY"]
    weather = ["sunny", "cloudy", "rain", "windy", "snow"]
    rows: List[Tuple] = []
    now = datetime.now()
    start_base = now - timedelta(days=360)
    for _ in range(screening_count):
        cinema_id = rng.randint(1, cinema_count)
        movie_id = rng.randint(1, movie_count)
        start_time = random_datetime_between(rng, start_base, now + timedelta(days=10))
        duration = timedelta(minutes=rng.randint(90, 210))
        end_time = start_time + duration
        base_price = round(rng.uniform(29, 138), 2)
        seat_capacity = rng.randint(60, 380)
        sold_tickets = rng.randint(0, seat_capacity)
        rows.append(
            (
                cinema_id,
                movie_id,
                rng.choice(screen_types),
                start_time,
                end_time,
                base_price,
                seat_capacity,
                sold_tickets,
                rng.choice(weather),
            )
        )
    return rows


def seed_customers(rng: random.Random, customer_count: int, city_count: int) -> List[Tuple]:
    membership_levels = ["normal", "silver", "gold", "platinum"]
    rows: List[Tuple] = []
    for i in range(customer_count):
        city_id = rng.randint(1, city_count)
        customer_name = f"User_{i + 1:06d}"
        gender = rng.choice(["M", "F"])
        birth_year = rng.randint(1965, 2010)
        register_date = date.today() - timedelta(days=rng.randint(1, 2500))
        level = rng.choices(
            population=membership_levels,
            weights=[0.55, 0.25, 0.15, 0.05],
            k=1,
        )[0]
        total_spent = round(rng.uniform(0, 12000), 2)
        is_active = 1 if rng.random() > 0.08 else 0
        rows.append(
            (
                city_id,
                customer_name,
                gender,
                birth_year,
                register_date,
                level,
                total_spent,
                is_active,
            )
        )
    return rows


def seed_orders_and_items(
    rng: random.Random,
    order_count: int,
    customer_count: int,
    screenings: Sequence[Tuple],
) -> Tuple[List[Tuple], List[Tuple]]:
    payment_methods = ["wechat", "alipay", "card", "cash"]
    order_statuses = ["paid", "completed", "refunded", "partial_refund"]
    channels = ["app", "web", "kiosk", "counter"]
    discounts = ["none", "coupon", "member", "campaign"]
    snacks = ["none", "cola_popcorn", "nachos_combo", "coffee_combo", "family_bucket"]

    screening_prices = [row[5] for row in screenings]
    screening_starts = [row[3] for row in screenings]

    order_rows: List[Tuple] = []
    item_rows: List[Tuple] = []
    for order_idx in range(order_count):
        customer_id = rng.randint(1, customer_count)
        screening_id = rng.randint(1, len(screenings))
        start_time = screening_starts[screening_id - 1]
        order_time = start_time - timedelta(hours=rng.randint(1, 96), minutes=rng.randint(0, 59))
        ticket_count = rng.choices([1, 2, 3, 4], weights=[0.35, 0.4, 0.18, 0.07], k=1)[0]
        base_price = screening_prices[screening_id - 1]
        order_status = rng.choices(
            order_statuses, weights=[0.45, 0.43, 0.07, 0.05], k=1
        )[0]

        total_amount = 0.0
        item_payloads: List[Tuple] = []
        for _ in range(ticket_count):
            ticket_price = round(base_price * rng.uniform(0.75, 1.2), 2)
            total_amount += ticket_price
            seat_no = f"{chr(rng.randint(65, 75))}{rng.randint(1, 20):02d}"
            discount_type = rng.choices(discounts, weights=[0.55, 0.18, 0.17, 0.1], k=1)[0]
            snack_combo = rng.choices(snacks, weights=[0.65, 0.14, 0.09, 0.08, 0.04], k=1)[0]
            item_payloads.append((order_idx + 1, seat_no, ticket_price, discount_type, snack_combo))

        total_amount = round(total_amount, 2)
        refund_amount = 0.0
        if order_status == "refunded":
            refund_amount = total_amount
        elif order_status == "partial_refund":
            refund_amount = round(total_amount * rng.uniform(0.2, 0.8), 2)

        order_rows.append(
            (
                customer_id,
                screening_id,
                order_time,
                ticket_count,
                total_amount,
                rng.choice(payment_methods),
                order_status,
                rng.choice(channels),
                refund_amount,
            )
        )
        item_rows.extend(item_payloads)

    return order_rows, item_rows


def seed_reviews(
    rng: random.Random,
    review_count: int,
    movie_count: int,
    cinema_count: int,
    customer_count: int,
) -> List[Tuple]:
    templates = [
        "Story pacing is stable and easy to follow.",
        "Visual effects stand out in this screening.",
        "Character setup feels a bit weak in the first half.",
        "Sound design and soundtrack are above expectation.",
        "Overall experience is decent for weekend viewing.",
        "The ending is surprising and sparks discussion.",
    ]
    now = datetime.now()
    start_base = now - timedelta(days=450)

    rows: List[Tuple] = []
    for _ in range(review_count):
        rating = rng.randint(1, 10)
        if rating >= 8:
            sentiment = "positive"
        elif rating >= 5:
            sentiment = "neutral"
        else:
            sentiment = "negative"
        rows.append(
            (
                rng.randint(1, movie_count),
                rng.randint(1, cinema_count),
                rng.randint(1, customer_count),
                rating,
                sentiment,
                random_datetime_between(rng, start_base, now),
                rng.choice(templates),
                rng.randint(0, 1200),
            )
        )
    return rows


def seed_all(conn: psycopg.Connection, args: argparse.Namespace) -> Dict[str, int]:
    rng = random.Random(args.seed)
    summary: Dict[str, int] = {}

    city_rows = seed_cities(rng, args.city_count)
    insert_many(
        conn,
        """
        INSERT INTO cities (city_name, region, tier, population, gdp_billion)
        VALUES (%s, %s, %s, %s, %s)
        """,
        city_rows,
        args.batch_size,
    )
    summary["cities"] = len(city_rows)

    cinema_rows = seed_cinemas(rng, args.cinema_count, args.city_count)
    insert_many(
        conn,
        """
        INSERT INTO cinemas (
            city_id, cinema_name, brand, address, opened_date,
            hall_count, seat_count, service_score
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        cinema_rows,
        args.batch_size,
    )
    summary["cinemas"] = len(cinema_rows)

    movie_rows = seed_movies(rng, args.movie_count)
    insert_many(
        conn,
        """
        INSERT INTO movies (
            title, genre, language, production_country, director,
            duration_min, release_date, imdb_score, box_office_million
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        movie_rows,
        args.batch_size,
    )
    summary["movies"] = len(movie_rows)

    screening_rows = seed_screenings(rng, args.screening_count, args.cinema_count, args.movie_count)
    insert_many(
        conn,
        """
        INSERT INTO screenings (
            cinema_id, movie_id, screen_type, start_time, end_time,
            base_price, seat_capacity, sold_tickets, city_weather
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        screening_rows,
        args.batch_size,
    )
    summary["screenings"] = len(screening_rows)

    customer_rows = seed_customers(rng, args.customer_count, args.city_count)
    insert_many(
        conn,
        """
        INSERT INTO customers (
            city_id, customer_name, gender, birth_year, register_date,
            membership_level, total_spent, is_active
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        customer_rows,
        args.batch_size,
    )
    summary["customers"] = len(customer_rows)

    order_rows, item_rows = seed_orders_and_items(
        rng=rng,
        order_count=args.order_count,
        customer_count=args.customer_count,
        screenings=screening_rows,
    )
    insert_many(
        conn,
        """
        INSERT INTO ticket_orders (
            customer_id, screening_id, order_time, ticket_count, total_amount,
            payment_method, order_status, sales_channel, refund_amount
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        """,
        order_rows,
        args.batch_size,
    )
    summary["ticket_orders"] = len(order_rows)

    insert_many(
        conn,
        """
        INSERT INTO order_items (
            order_id, seat_no, ticket_price, discount_type, snack_combo
        ) VALUES (%s, %s, %s, %s, %s)
        """,
        item_rows,
        args.batch_size,
    )
    summary["order_items"] = len(item_rows)

    review_rows = seed_reviews(
        rng=rng,
        review_count=args.review_count,
        movie_count=args.movie_count,
        cinema_count=args.cinema_count,
        customer_count=args.customer_count,
    )
    insert_many(
        conn,
        """
        INSERT INTO movie_reviews (
            movie_id, cinema_id, customer_id, rating, sentiment,
            review_time, content, like_count
        ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        """,
        review_rows,
        args.batch_size,
    )
    summary["movie_reviews"] = len(review_rows)

    return summary


def validate_args(args: argparse.Namespace) -> None:
    int_fields = [
        ("city-count", args.city_count),
        ("cinema-count", args.cinema_count),
        ("movie-count", args.movie_count),
        ("screening-count", args.screening_count),
        ("customer-count", args.customer_count),
        ("order-count", args.order_count),
        ("review-count", args.review_count),
        ("batch-size", args.batch_size),
    ]
    for name, value in int_fields:
        if value <= 0:
            raise ValueError(f"{name} must be greater than 0")


def main() -> None:
    args = parse_args()
    validate_args(args)
    conn = connect_database(args)
    try:
        create_tables(conn, recreate=args.recreate)
        summary = seed_all(conn, args)
    finally:
        conn.close()

    print(f"Schema ready in database: {args.database}")
    for table_name, row_count in summary.items():
        print(f"- {table_name}: {row_count}")


if __name__ == "__main__":
    main()